name: Windows Build

on:
  workflow_call:
    inputs:
      ring-version:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
        - arch: x64
          arch_name: amd64

    steps:
    - name: Checkout ring-libsql
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Checkout Ring Language
      uses: actions/checkout@v4
      with:
        repository: ring-lang/ring
        path: ring
        ref: ${{ inputs.ring-version }}

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Configure and Build Ring Language for ${{ matrix.arch_name }}
      shell: cmd
      run: |
        cd ring\language
        REM Use the matrix variable to set the architecture
        cmake . -A ${{ matrix.arch }}
        cmake --build . --config Release --parallel
        cmake --install .

    - name: Set RING environment variable
      run: echo "RING=$(pwd)\ring" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Configure and Build ring-libsql lib for ${{ matrix.arch_name }}
      shell: cmd
      run: |
        if exist lib rmdir /s /q lib
        cmake . -A ${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release --parallel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ring-libsql-windows-${{ matrix.arch_name }}
        path: lib
